# Generated by Django 4.2.3 on 2023-07-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcuser',
            options={'verbose_name': '부트캠퍼스 사용자', 'verbose_name_plural': '부트캠퍼스 사용자'},
        ),
        migrations.RemoveField(
            model_name='bcuser',
            name='registered_dttm',
        ),
        migrations.AddField(
            model_name='bcuser',
            name='useremail',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='bcuser',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='사용자명'),
        ),
    ]
