# Generated by Django 4.2.3 on 2023-07-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcuser', '0002_alter_bcuser_options_remove_bcuser_registered_dttm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcuser',
            name='useremail',
            field=models.EmailField(max_length=128, verbose_name='사용자이메일'),
        ),
    ]
