# Generated by Django 4.2.3 on 2023-08-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publicShed_date',
            new_name='publiShed_date',
        ),
    ]
