# Generated by Django 4.2.3 on 2023-08-02 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcuser', '0001_initial'),
        ('blog', '0002_rename_publicshed_date_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcuser.bcuser', verbose_name='작성자'),
        ),
    ]
